language: r
cache: packages

install:
  - R -e 'install.packages("devtools", repos = "https://cloud.r-project.org")'
  - R -e "devtools::install_deps(dependencies = TRUE)"

script:
  - R CMD build .
  - R CMD check *tar.gz --as-cran

warnings_are_errors: true
