# .travis.yml for R package

language: R  # Specify the language as R

cache: packages  # Cache installed packages to speed up builds

# Specify R versions to test against
r:
  - release  # Latest stable release of R
  - devel    # Development version of R (optional)


# Install R package dependencies
install:
  - R -e "install.packages('devtools', repos = 'https://cloud.r-project.org')"
  - R -e "devtools::install_deps(dependencies = TRUE)"

# Run R CMD check
script:
  - R -e "devtools::check()"


