language: r
cache: packages
r:
  - release

install:
  - R -e 'install.packages("remotes", repos = "https://cloud.r-project.org")'
  - R -e "remotes::install_deps(dependencies = TRUE)"

script:
  - R CMD build .
  - R CMD check *tar.gz --as-cran

warnings_are_errors: true
