language: r

before_install:
  - R -e "install.packages('devtools', repos = 'https://cloud.r-project.org')"

install:
  - R -e "devtools::install_deps(dependencies = TRUE)"

script:
  - R CMD build .
  - R CMD check *tar.gz

# Optionally, you can specify the R version if needed
r:
  - release
  - devel
